import {chromium} from '@playwright/test';
import {browserOptions} from './browser-support.mjs';
import assert from 'node:assert/strict';
import {pathToFileURL} from 'node:url';
import {resolve} from 'node:path';
import {writeFile} from 'node:fs/promises';
const browser=await chromium.launch(await browserOptions());const context=await browser.newContext({viewport:{width:1366,height:768}});const page=await context.newPage(),errors=[],external=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(!r.url().startsWith('http://localhost:4173')&&!r.url().startsWith('data:'))external.push(r.url());});
await page.goto('http://localhost:4173');await page.locator('[data-action="stages"]').first().waitFor();await page.evaluate(()=>navigator.serviceWorker.ready);await page.waitForFunction(()=>navigator.serviceWorker.controller!==null);assert.equal(await page.evaluate(()=>typeof window.__goldward),'undefined');
await page.reload();await page.locator('[data-action="stages"]').first().waitFor();
// Warm installed browser: disconnect ALL HTTP and verify cache-only reload.
await context.setOffline(true);await page.reload();await page.locator('[data-action="stages"]').first().waitFor();await page.locator('[data-action="stages"]').first().click();await page.locator('[data-action="team"]').click();await page.locator('[data-action="battle"]').click();await page.locator('[data-action="site"][data-id="0"]').click();await page.locator('[data-action="deselect"]').click();await page.locator('[data-action="wave"]').click();await page.waitForTimeout(1500);await page.screenshot({path:'artifacts/screenshots/offline-battle.png'});assert.deepEqual(errors,[]);assert.deepEqual(external,[]);
await writeFile('artifacts/offline-report.json',JSON.stringify({installedBrowserOfflineReload:'PASS',offlineBattle:'PASS',debugAbsent:'PASS',externalRequests:external,errors,standaloneFile:'Tested separately below with fresh browser storage and all network disabled; dist/offline.html needs no server'},null,2));console.log('PASS: production, no debug, no external requests, cached offline reload + battle');const fresh=await browser.newContext({offline:true});const file=await fresh.newPage();await file.goto(pathToFileURL(resolve('dist/offline.html')).href);await file.locator('[data-action="stages"]').first().waitFor();await file.locator('[data-action="stages"]').first().click();await file.locator('[data-action="team"]').click();await file.locator('[data-action="battle"]').click();await file.locator('[data-action="wave"]').click();await file.waitForTimeout(300);console.log('PASS: standalone HTML, fresh storage, network disabled, no local server');await browser.close();
