import {chromium} from '@playwright/test';
import {browserOptions} from './browser-support.mjs';
import {writeFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const browser=await chromium.launch(await browserOptions());const page=await browser.newPage({viewport:{width:1366,height:768}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://localhost:5173');await page.locator('[data-action="stages"]').first().waitFor();
await page.evaluate(async()=>{const {ENEMIES}=await import('/src/data.js');const {onPath}=await import('/src/engine.js');window.__goldward.start();const b=window.__goldward.battle;b.gold=10000;for(let i=0;i<10;i++){b.place(i,['archer','cannon','frost','storm','flame','gold'][i%6]);b.upgrade(i);b.upgrade(i);}b.nextWave();b.spawnQueue=[];for(let i=0;i<200;i++){const d=i*7;b.enemies.push({...ENEMIES.brute,type:'brute',id:++b.id,hp:5000,maxHP:5000,distance:d,...onPath(d),flash:0,slow:0,freeze:0,phase:0});}});
await page.waitForTimeout(6000);const stress=await page.evaluate(()=>window.__goldward.metrics);await page.screenshot({path:'artifacts/screenshots/stress-200.png'});assert.ok(stress.particles<=450);assert.ok(stress.projectiles<100);assert.ok(stress.enemies<=200);
await page.evaluate(()=>{window.__goldward.start();const b=window.__goldward.battle;b.gold=10000;for(let i=0;i<10;i++){b.place(i,i%2?'cannon':'archer');b.upgrade(i);b.upgrade(i);}for(let i=0;i<70000&&!['victory','defeat'].includes(b.state);i++){if(!b.enemies.length&&!b.spawnQueue.length)b.nextWave();b.step(1/60);b.events=[];if(b.enemies.some(e=>e.type==='boss'&&e.distance>250))break;}b.pause=true;});
await page.waitForTimeout(200);await page.screenshot({path:'artifacts/screenshots/boss.png'});
for(let i=0;i<40;i++){await page.evaluate(()=>{window.__goldward.action('confirm-leave');window.__goldward.action('collection');window.__goldward.action('shop');window.__goldward.action('team');window.__goldward.start();});}const after=await page.evaluate(()=>window.__goldward.metrics);assert.ok(after.enemies===0);assert.ok(after.projectiles===0);assert.ok(after.particles===0);
// Actual unopposed loss and recovery, not a painted result screen.
await page.evaluate(()=>{const b=window.__goldward.battle;for(let i=0;i<60000&&b.state!=='defeat';i++){if(!b.enemies.length&&!b.spawnQueue.length)b.nextWave();b.step(1/60);} });await page.locator('[data-action="restart"]').waitFor();await page.screenshot({path:'artifacts/screenshots/defeat.png'});await page.locator('[data-action="restart"]').click();assert.equal(await page.evaluate(()=>window.__goldward.battle.state),'ready');
await page.evaluate(()=>{localStorage.setItem('goldward.save','{corrupt');localStorage.setItem('goldward.save.backup',JSON.stringify({version:1,gold:777,gems:50}));});await page.reload();await page.locator('[data-action="stages"]').first().waitFor();assert.equal(await page.evaluate(()=>window.__goldward.save.gold),777);
assert.deepEqual(errors,[]);await writeFile('artifacts/stress-report.json',JSON.stringify({stress,afterRestarts:after,restarts:40,errors,saveBackupRecovery:'PASS',defeatRestart:'PASS',note:'Headless software rendering. No physical device, battery, heap-retention or long-duration memory certification.'},null,2));console.log({stress,after,errors});await browser.close();
