import {TOWERS,HEROES,ENEMIES,PATH,SITES,STAGES,waveData} from './data.js';
export function rng(seed){let s=seed>>>0;return()=>{s=(s*1664525+1013904223)>>>0;return s/4294967296;};}
const segments=PATH.slice(1).map((p,i)=>Math.hypot(p[0]-PATH[i][0],p[1]-PATH[i][1]));
export const pathLength=segments.reduce((a,b)=>a+b,0);
export function onPath(distance){for(let i=0;i<segments.length;i++){if(distance<=segments[i]){const f=distance/segments[i];return {x:PATH[i][0]+(PATH[i+1][0]-PATH[i][0])*f,y:PATH[i][1]+(PATH[i+1][1]-PATH[i][1])*f,flip:PATH[i+1][0]<PATH[i][0]};}distance-=segments[i];}return {x:1320,y:490,flip:false};}
export class Battle{
 constructor({stage=1,seed=918273,hero='lyra',levels={},team=TOWERS.map(t=>t.id)}={}){this.stage=STAGES.find(s=>s.id===stage)||STAGES[0];this.seed=seed;this.random=rng(seed);this.hero=HEROES.find(h=>h.id===hero)||HEROES[0];this.levels=levels;this.team=team;this.state='ready';this.time=0;this.wave=0;this.gold=420;this.lives=20;this.kills=0;this.towers=[];this.enemies=[];this.shots=[];this.events=[];this.actions=[];this.skillCD=0;this.heroUnit={x:1130,y:420,cd:0,attack:0};this.id=0;this.waveTime=0;this.spawnQueue=[];this.pause=false;this.speed=1;}
 emit(type,data={}){this.events.push({type,...data});}
 place(site,id){const t=TOWERS.find(t=>t.id===id);if(!['ready','running'].includes(this.state)||this.pause||!Number.isInteger(site)||!SITES[site]||this.towers.some(t=>t.site===site)||!t||!this.team.includes(id)||this.gold<t.cost)return false;this.gold-=t.cost;this.towers.push({id,site,x:SITES[site][0],y:SITES[site][1],level:1,cd:.2,attack:0,targeting:'first'});this.actions.push({at:this.time,type:'place',site,id});this.emit('build',{x:SITES[site][0],y:SITES[site][1]});return true;}
 upgrade(site){const t=this.towers.find(t=>t.site===site);if(this.pause||!['ready','running'].includes(this.state)||!t||t.level>=3)return false;const cost=this.upgradeCost(t);if(this.gold<cost)return false;this.gold-=cost;t.level++;this.actions.push({at:this.time,type:'upgrade',site});this.emit('upgrade',t);return true;}
 upgradeCost(t){return Math.floor(TOWERS.find(d=>d.id===t.id).cost*(.65+t.level*.25));}
 sell(site){const t=this.towers.find(t=>t.site===site);if(this.pause||!['ready','running'].includes(this.state)||!t)return false;this.gold+=Math.floor(TOWERS.find(d=>d.id===t.id).cost*.65*t.level);this.towers=this.towers.filter(x=>x!==t);this.actions.push({at:this.time,type:'sell',site});return true;}
 nextWave(){if(this.pause||!['ready','running'].includes(this.state)||this.enemies.length||this.spawnQueue.length||this.wave>=this.stage.waves)return false;this.state='running';this.wave++;this.waveTime=0;this.spawnQueue=waveData(this.stage,this.wave);this.actions.push({at:this.time,type:'wave'});this.emit(this.wave===this.stage.waves?'boss-warning':'wave',{wave:this.wave});return true;}
 skill(){if(this.pause||this.state!=='running'||this.skillCD>0||!this.enemies.length)return false;this.skillCD=this.hero.cooldown;this.actions.push({at:this.time,type:'skill'});this.emit('skill',{hero:this.hero.id});for(const e of this.enemies){this.hit(e,this.hero.damage,true);if(this.hero.freeze)e.freeze=this.hero.freeze;}this.cleanup();return true;}
 hit(e,damage,pierce=false){if(e.hp<=0)return;e.hp-=Math.max(1,damage-(pierce?0:e.armor));e.flash=.12;this.emit('hit',{x:e.x,y:e.y,damage:Math.round(damage),boss:e.type==='boss'});}
 cleanup(){this.enemies=this.enemies.filter(e=>{if(e.hp>0)return true;this.gold+=e.reward;this.kills++;this.emit('death',{x:e.x,y:e.y,enemy:e.type,reward:e.reward});return false;});}
 step(dt){if(this.pause||!['ready','running'].includes(this.state)||!Number.isFinite(dt)||dt<=0)return;dt=Math.min(dt,.05);this.time+=dt;this.skillCD=Math.max(0,this.skillCD-dt);if(this.state==='ready')return;this.waveTime+=dt;
 while(this.spawnQueue.length&&this.spawnQueue[0].at<=this.waveTime){const {type}=this.spawnQueue.shift(),d=ENEMIES[type];this.enemies.push({...d,type,id:++this.id,hp:d.hp*this.stage.modifier,maxHP:d.hp*this.stage.modifier,distance:0,...onPath(0),flash:0,slow:0,freeze:0,phase:0});if(type==='boss')this.emit('boss',{name:d.name});}
 for(const e of this.enemies){e.flash=Math.max(0,e.flash-dt);e.slow=Math.max(0,e.slow-dt);e.freeze=Math.max(0,e.freeze-dt);if(e.type==='boss'&&e.hp<e.maxHP*.45&&!e.phase){e.phase=1;this.emit('enrage',{x:e.x,y:e.y});}e.distance+=e.speed*dt*(e.slow>0?.48:1)*(e.freeze>0?0:1)*(e.phase?1.35:1);Object.assign(e,onPath(e.distance));}
 this.enemies=this.enemies.filter(e=>{if(e.distance<pathLength)return true;this.lives=Math.max(0,this.lives-e.damage);this.emit('leak',{x:1190,y:490});return false;});
 for(const t of this.towers){t.cd-=dt;t.attack=Math.max(0,t.attack-dt);if(t.cd>0)continue;const d=TOWERS.find(d=>d.id===t.id),range=d.range+(t.level-1)*14;const candidates=this.enemies.filter(e=>e.hp>0&&Math.hypot(e.x-t.x,e.y-t.y)<range);candidates.sort(t.targeting==='strongest'?(a,b)=>b.hp-a.hp:(a,b)=>b.distance-a.distance);const target=candidates[0];if(!target)continue;t.cd=d.rate/(1+(t.level-1)*.14);t.attack=.22;const damage=d.damage*(1+(t.level-1)*.7)*(1+((this.levels[t.id]||1)-1)*.08);this.shots.push({x:t.x,y:t.y-52,target:target.id,damage,kind:d.projectile,splash:d.splash||0,chain:d.chain||0,slow:d.slow,pierce:d.pierce,life:2});this.emit('attack',{kind:d.projectile,x:t.x,y:t.y});}
 const h=this.heroUnit;h.cd-=dt;h.attack=Math.max(0,h.attack-dt);const threat=this.enemies.filter(e=>e.hp>0&&Math.hypot(e.x-1130,e.y-420)<330).sort((a,b)=>b.distance-a.distance)[0];
 const hx=threat?Math.min(1170,Math.max(960,threat.x+95)):1130,hy=threat?Math.min(500,Math.max(320,threat.y-45)):420;const hd=Math.hypot(hx-h.x,hy-h.y);if(hd>3){h.x+=(hx-h.x)/hd*Math.min(hd,dt*75);h.y+=(hy-h.y)/hd*Math.min(hd,dt*75);}
 if(threat&&h.cd<=0&&Math.hypot(threat.x-h.x,threat.y-h.y)<250){h.cd=1.2;h.attack=.25;this.shots.push({x:h.x,y:h.y-40,target:threat.id,damage:24,kind:this.hero.id==='lyra'?'arrow':this.hero.id==='orin'?'fire':'ice',splash:this.hero.id==='orin'?40:0,slow:this.hero.id==='astra',life:2});this.emit('attack',{kind:'hero',x:h.x,y:h.y});}
 for(const p of this.shots){p.life-=dt;const e=this.enemies.find(e=>e.id===p.target);if(!e){p.life=0;continue;}const dx=e.x-p.x,dy=e.y-20-p.y,dist=Math.hypot(dx,dy),speed=p.kind==='bolt'?1100:440;if(dist<speed*dt+8){p.life=0;this.hit(e,p.damage,p.pierce);if(p.slow)e.slow=2;if(p.splash)for(const other of this.enemies)if(other!==e&&Math.hypot(other.x-e.x,other.y-e.y)<p.splash)this.hit(other,p.damage*.65);if(p.chain){let count=0;for(const other of this.enemies)if(other!==e&&count<p.chain&&Math.hypot(other.x-e.x,other.y-e.y)<140){this.hit(other,p.damage*.6);this.emit('arc',{x:e.x,y:e.y,x2:other.x,y2:other.y});count++;}}this.emit('impact',{x:e.x,y:e.y-15,kind:p.kind});}else{p.x+=dx/dist*speed*dt;p.y+=dy/dist*speed*dt;p.angle=Math.atan2(dy,dx);}}
 this.shots=this.shots.filter(p=>p.life>0);this.cleanup();if(this.lives<=0){this.state='defeat';this.emit('defeat');}else if(this.wave===this.stage.waves&&!this.enemies.length&&!this.spawnQueue.length){this.state='victory';this.emit('victory');}if(this.events.length>800)this.events.splice(0,this.events.length-800);
 }
 snapshot(){return {seed:this.seed,stage:this.stage.id,time:this.time,wave:this.wave,gold:this.gold,lives:this.lives,state:this.state,hero:this.hero.id,heroUnit:this.heroUnit,levels:this.levels,team:this.team,towers:this.towers,enemies:this.enemies,shots:this.shots,actions:this.actions};}
}

export function replay(record){const b=new Battle({stage:record.stage,seed:record.seed,hero:record.hero,levels:record.levels,team:record.team});const queue=[...record.actions];while(b.time+1e-8<record.time&&['ready','running'].includes(b.state)){while(queue.length&&queue[0].at<=b.time+1e-8){const a=queue.shift();if(a.type==='place')b.place(a.site,a.id);if(a.type==='upgrade')b.upgrade(a.site);if(a.type==='sell')b.sell(a.site);if(a.type==='wave')b.nextWave();if(a.type==='skill')b.skill();if(a.type==='targeting'){const t=b.towers.find(t=>t.site===a.site);if(t)t.targeting=a.value;}}b.step(1/60);b.events=[];}return b;}
