import './style.css';
import {TOWERS,HEROES,STAGES,SITES,validateContent} from './data.js';
import {Battle,rng} from './engine.js';
import {load,persist,spend,grant} from './save.js';
import {icon,towerSVG,heroSVG,loadArt,mapArt} from './art.js';
import {Renderer} from './render.js';
import {AudioSystem} from './audio.js';
const ui=document.querySelector('#ui'),canvas=document.querySelector('#world'),toastElement=document.querySelector('#toast');
let save=load(),screen='loading',stage=1,battle=null,selected=-1,build='archer',modal=null,resultClaimed=false,toastUntil=0,last=0,accumulator=0,hudTime=0,renderCount=0,fps=60,lastRenderedScreen='';
const renderer=new Renderer(canvas),audio=new AudioSystem();audio.enabled=save.sound;
const btn=(label,action,cls='primary',attrs='')=>`<button class="${cls}" data-action="${action}" ${attrs}>${label}</button>`;
const resource=(type,value,id='')=>`<div class="resource">${icon(type)}<span ${id?`id="${id}"`:''}>${value.toLocaleString('en-US')}</span></div>`;
function notify(text){toastElement.textContent=text;toastElement.classList.add('show');toastUntil=performance.now()+2800;}
function store(){if(!persist(save))notify('Storage unavailable. Progress is kept for this session only.');}
function topbar(){return `<header class="topbar"><div class="identity"><div class="crest">${icon('shield')}</div><div><strong>GOLDWARD</strong><span class="small">THE WOODLAND CHRONICLES</span></div></div><div class="resources">${resource('coin',save.gold)}${resource('gem',save.gems)}${btn(icon(save.sound?'sound':'cross'),'sound','round','aria-label="Toggle sound"')}</div></header>`;}
function screenHeader(title,subtitle){return `<div class="screen-shade"></div>${topbar()}<div class="screen-heading" style="top:12%">${btn(icon('back'),'home','round','aria-label="Return home"')}<div><h2>${title}</h2><p>${subtitle}</p></div></div>`;}
function home(){return `${topbar()}<div class="home-title"><div class="wood-sign"><h1><span>DEFEND THE</span>GOLDWARD</h1><p>SMALL TOWERS. LEGENDARY DEFENDERS.</p></div></div><aside class="home-note"><div class="eyebrow">CHAPTER ONE</div><h3>The wild is waking.</h3><p>Build your defenses.<br>Protect the last of the gold.</p></aside><div class="home-start">${btn(icon('sword')+' Play','stages')}<p>YOUR ADVENTURE AWAITS</p></div><nav class="bottom-nav" aria-label="Main navigation">${[['shield','Team','team'],['tower','Armory','collection'],['chest','Summon','shop'],['book','Field guide','guide'],['gear','Settings','settings']].map(([i,n,a])=>btn(`<span class="nav-medallion">${icon(i)}</span><span>${n}</span>`,a,'nav-item')).join('')}</nav><div class="offline-label">Independent edition &nbsp;•&nbsp; All progress saved locally</div>`;}
const nodePositions=[[8,57],[16,30],[25,49],[33,72],[40,41],[49,21],[57,49],[64,76],[73,54],[80,28],[88,47],[94,72]];
function stages(){return `${screenHeader('Select stage','Chapter I · The Woodland Frontier')}<section class="screen-body parchment" style="top:23%"><div class="map-header"><span>The Woodland Frontier</span></div>${mapArt()}<div class="stage-map"><svg class="map-route" viewBox="0 0 1000 300" preserveAspectRatio="none"><g stroke="#8b7747" fill="none"><path stroke-width="2" d="M0 70L160 5l55 54 120-55 95 94L590 8l105 70L880 0l120 65M0 240l100-44 107 80 123-21 90 45 70-50 100 50 100-60 160 50 150-25"/><path stroke-width="7" stroke-dasharray="4 9" stroke-linecap="round" d="${nodePositions.map(([x,y],i)=>`${i?'L':'M'}${x*10} ${y*3}`).join(' ')}"/></g></svg>${STAGES.map((s,i)=>`<button class="stage-node ${s.id===stage?'current':''} ${s.id>save.unlocked?'locked':''}" style="left:${nodePositions[i][0]}%;top:${nodePositions[i][1]}%" data-action="stage" data-id="${s.id}" ${s.id>save.unlocked?'disabled':''} aria-label="Stage ${s.id}: ${s.name}${s.id>save.unlocked?', locked':''}"><span class="stage-seal">${s.id}</span><span class="stars ${save.stars[s.id]?'earned':''}">${'★'.repeat(save.stars[s.id]||0)}${'☆'.repeat(3-(save.stars[s.id]||0))}</span></button>`).join('')}</div><div class="stage-summary"><div><span class="eyebrow">STAGE ${stage.toString().padStart(2,'0')}</span><br><strong>${STAGES[stage-1].name}</strong></div><span>${STAGES[stage-1].waves} waves &nbsp;·&nbsp; ${icon('coin')} ${STAGES[stage-1].reward} reward</span></div></section><footer class="screen-footer"><span class="small">${Object.values(save.stars).reduce((a,b)=>a+b,0)} / 36 stars collected · Clear stages to unlock the frontier.</span>${btn('Prepare defenses '+icon('sword'),'team')}</footer>`;}
function team(){const h=HEROES.find(h=>h.id===save.hero);return `${screenHeader('Prepare your team','Choose a hero and four towers for the journey.')}<section class="screen-body team-layout" style="top:23%"><div class="hero-panel panel"><div class="hero-art">${heroSVG(h.id)}</div><h3>${h.name}</h3><p>${h.title}</p><div class="hero-selector">${HEROES.map(h=>btn(h.name,'hero',h.id===save.hero?'active':'',`data-id="${h.id}"`)).join('')}</div></div><div class="tower-grid">${TOWERS.map(t=>`<button class="tower-card ${save.team.includes(t.id)?'selected':''}" data-action="team-tower" data-id="${t.id}" aria-pressed="${save.team.includes(t.id)}"><div class="rarity ${t.rarity.toLowerCase()}">${t.rarity}</div><div class="tower-art">${towerSVG(t.id)}</div><h3>${t.name}</h3><p>${t.role}</p></button>`).join('')}</div></section><footer class="screen-footer"><span class="small">${h.skill} · ${h.description}<br>${save.team.length}/4 towers selected · Stage ${stage}: ${STAGES[stage-1].name}</span>${btn('To battle '+icon('sword'),'battle','primary',save.team.length!==4?'disabled':'')}</footer>`;}
function collection(){return `${screenHeader('The armory','Permanent training carries into every battle.')}<section class="screen-body collection-grid" style="top:24%">${TOWERS.map(t=>{const level=save.levels[t.id],cost=level*100;return `<article class="tower-card"><div class="rarity ${t.rarity.toLowerCase()}">${t.rarity}</div><div class="tower-art">${towerSVG(t.id)}</div><h3>${t.name}</h3><p>Level ${level} / 20</p><div class="stats"><span>${icon('sword')} ${Math.round(t.damage*(1+(level-1)*.08))}</span><span>${t.rate}s</span></div><p>${t.role}</p>${btn(level>=20?'MAX LEVEL':`${icon('coin')} ${cost} · Train`,'train','secondary',`data-id="${t.id}" ${level>=20||save.gold<cost?'disabled':''}`)}</article>`;}).join('')}</section><footer class="screen-footer"><span class="small">Each level grants +8% base damage. Battle upgrades are separate.</span>${btn('Prepare team '+icon('shield'),'team')}</footer>`;}
function shop(){return `${screenHeader('The wishing vault','Local rewards only · No purchases, ads, or online services.')}<section class="screen-body shop-layout" style="top:24%"><div class="summon-panel panel">${icon('chest')}<div class="eyebrow">A GIFT FROM THE FRONTIER</div><h3>Defender’s chest</h3><p>Uncover a tower training card.<br>Each card raises one tower’s permanent level.</p>${btn(`${icon('gem')} 40 · Open chest`,'summon','primary',save.gems<40?'disabled':'')}<p class="credits">6 towers · Equal chance · Max-level duplicate: 100 gold</p></div><div class="shop-offers"><article class="offer panel">${icon('coin')}<div><h3>Traveler’s purse</h3><p>Exchange 30 gems for 300 gold.</p></div>${btn(icon('gem')+' 30','exchange','secondary',save.gems<30?'disabled':'')}</article><article class="offer panel">${icon('sword')}<div><h3>Earn it in battle</h3><p>Every victory awards gold.<br>First clears award 25 gems.</p></div>${btn('Play','stages','secondary')}</article><p class="small">The vault is deterministic for reproducible offline rewards.<br>Your resources never require a network connection.</p></div></section>`;}
function screenPoint(x,y){const portrait=matchMedia('(orientation: portrait)').matches;const box=document.querySelector('#game').getBoundingClientRect();return {left:x/1280*100,top:portrait?25+y/720*(box.width*.5625/box.height*100):y/720*100};}
function battleUI(){const s=battle.stage;return `<div class="battle-top"><div class="battle-left"><div class="battle-stats">${resource('heart',battle.lives,'lives')}${resource('coin',battle.gold,'battle-gold')}</div><div class="wave-label">${icon('sword')} WAVE <span id="wave-count">${battle.wave} / ${s.waves}</span></div></div><div class="battle-controls">${btn('1×','speed','round','id="speed" aria-label="Toggle battle speed"')}${btn(icon('pause'),'pause','round','aria-label="Pause battle"')}</div></div><div class="battle-title"><strong>${s.name}</strong><p>STAGE ${s.id.toString().padStart(2,'0')} · PROTECT THE GOLD</p></div><div id="boss-slot"></div>${SITES.map(([x,y],i)=>{const p=screenPoint(x,y);return `<button class="site-target" style="left:${p.left}%;top:${p.top}%" data-action="site" data-id="${i}" aria-label="Build site ${i+1}"></button>`;}).join('')}<div id="tower-context"></div>${battle.wave===0?'<div class="tutorial"><strong>Your watch begins here.</strong>Choose a tower below, then a + build site.<br>Build several towers before starting.<br>1–4 towers · Space pause · Q skill</div>':''}<footer class="battle-bottom"><div class="loadout">${save.team.map((id,i)=>{const t=TOWERS.find(t=>t.id===id);return `<button class="build-card ${id===build?'active':''}" data-action="build" data-id="${id}" aria-label="${t.name}, ${t.cost} gold" title="${t.name} · ${t.role}"><kbd>${i+1}</kbd>${towerSVG(id)}<span>${icon('coin')} ${t.cost}</span></button>`;}).join('')}</div><button class="skill-button" data-action="skill" aria-label="Hero skill: ${battle.hero.skill}">${heroSVG(save.hero)}<span id="skill-label">${battle.hero.skill} [Q]</span></button><div class="battle-hint"><strong id="hint-title">Choose a build site</strong><small id="hint-detail">${TOWERS.find(t=>t.id===build).name} selected · Tap a + to build</small></div>${btn('Start wave '+icon('play'),'wave','primary wave-button','id="wave-button"')}</footer>`;}
function towerContext(){const el=document.querySelector('#tower-context');if(!el)return;const t=battle.towers.find(t=>t.site===selected);if(!t){el.innerHTML='';return;}const d=TOWERS.find(d=>d.id===t.id),p=screenPoint(t.x, t.y-60);el.innerHTML=`<div class="tower-menu panel" style="left:${Math.max(15,Math.min(85,p.left))}%;top:${Math.max(36,p.top)}%">${btn(icon('cross'),'deselect','close-small','aria-label="Close tower details"')}<h3>${d.name}</h3><p>Level ${t.level} / 3 · ${d.role}</p><p>${icon('sword')} ${Math.round(d.damage*(1+(t.level-1)*.7)*(1+(save.levels[t.id]-1)*.08))} damage &nbsp; / &nbsp; Range ${d.range+(t.level-1)*14}</p><label>Target <select aria-label="Tower targeting" id="targeting"><option value="first" ${t.targeting==='first'?'selected':''}>First enemy</option><option value="strongest" ${t.targeting==='strongest'?'selected':''}>Strongest enemy</option></select></label><div class="actions">${btn(t.level===3?'Max level':`${icon('coin')} ${battle.upgradeCost(t)} Upgrade`,'upgrade','primary',t.level===3||battle.gold<battle.upgradeCost(t)?'disabled':'')}${btn('Sell '+Math.floor(d.cost*.65*t.level),'sell','secondary')}</div></div>`;}
function guide(){return `<h2>Defender’s field guide</h2><p>Enemies follow the winding road toward your gold cache. Build on marked sites; towers attack automatically.</p><p><b>Rangers</b> fire quickly. <b>Cannons</b> hit groups. <b>Frost</b> slows targets. <b>Storm</b> chains lightning. <b>Ember</b> burns groups. <b>Sun</b> ignores armor.</p><p>Clear a wave, then call the next. Spend battle gold on upgrades. Use your hero’s skill in a tight spot. The final wave brings Briarhorn.</p><p class="credits">Mouse / touch: select towers and sites<br>1–4: tower · Q: skill · Space / Escape: pause<br>Independent work, not affiliated with BUSIDOL. Original characters, artwork, audio, and rules tuning. Fidelity research is ongoing.</p>${btn('Understood','close')}`;}
function modalHTML(){if(!modal)return '';let content='';if(modal==='settings')content=`<h2>At the campfire</h2><p>Take a moment, defender.</p><div class="buttons">${btn(icon(save.sound?'sound':'cross')+` Sound ${save.sound?'on':'off'}`,'sound','secondary')}${btn('Field guide','guide','secondary')}${btn('Back to camp','close')}</div><p class="credits">Version 0.1 · Independent offline edition<br>Progress saved on this device.</p>`;if(modal==='guide')content=guide();if(modal==='pause')content=`<div class="eyebrow">THE FRONTIER CAN WAIT</div><h2>Battle paused</h2><p>All battle timers are stopped.</p><div class="buttons">${btn(icon('play')+' Resume','resume')}${btn('Restart stage','restart','secondary')}${btn('Leave battle','leave','secondary')}</div>`;if(modal==='leave')content=`<h2>Return to camp?</h2><p>This battle’s progress will be lost. Your permanent upgrades and collected rewards are safe.</p><div class="buttons">${btn('Stay and defend','resume')}${btn('Leave battle','confirm-leave','danger')}</div>`;if(modal==='victory'||modal==='defeat'){const win=modal==='victory',stars=battle.lives===20?3:battle.lives>=10?2:1;content=`<div class="eyebrow">${battle.stage.name}</div><h2>${win?'The gold is safe!':'The frontier has fallen'}</h2>${win?`<div class="reward-stars">${'★'.repeat(stars)}${'☆'.repeat(3-stars)}</div>`:icon('shield')}<p>${win?'A fine defense. The woodland remembers.':'Regroup, train your towers, and try a new defense.'}<br>${battle.kills} enemies defeated · ${Math.floor(battle.time)} seconds</p>${win?`<div class="divider"></div><div class="reward-value">${icon('coin')} ${battle.stage.reward}</div>${!save.stars[battle.stage.id]?`<div class="reward-value">${icon('gem')} 25</div>`:''}<div class="buttons">${btn('Claim rewards '+icon('chest'),'claim')}</div>`:`<div class="buttons">${btn('Try again','restart')}${btn('Return to camp','confirm-leave','secondary')}</div>`}`;}
 if(modal?.type==='summon'){const t=TOWERS.find(t=>t.id===modal.id);content=`<div class="eyebrow">THE VAULT HAS CHOSEN</div><h2>${t.name}</h2><div class="reveal-art">${towerSVG(t.id)}</div><div class="rarity ${t.rarity.toLowerCase()}">${t.rarity} TRAINING CARD</div><p>${modal.duplicate?'Already mastered · 100 gold returned':`Permanent level increased to ${save.levels[t.id]}`}</p>${btn('Wonderful','close')}`;}
 return `<div class="modal-backdrop"><section class="modal panel" role="dialog" aria-modal="true" aria-label="${typeof modal==='string'?modal:'Reward'}">${content}</section></div>`;}
function renderUI(){const views={home,stages,team,collection,shop,battle:battleUI,loading:()=>`<div class="loading">${icon('tower')}<strong>Preparing the frontier</strong><div class="loading-line"></div></div>`};ui.innerHTML=views[screen]()+modalHTML();if(screen==='battle'){towerContext();updateHUD();}if(modal)requestAnimationFrame(()=>ui.querySelector('.modal button')?.focus());}
function navigate(next){modal=null;if(screen==='team'&&save.team.length!==4)save.team=['archer','cannon','frost','storm'];screen=next;selected=-1;store();renderUI();}
function startBattle(){if(save.team.length!==4)return;stage=Math.min(stage,save.unlocked);battle=new Battle({stage,seed:918273+stage,hero:save.hero,levels:{...save.levels},team:[...save.team]});build=save.team[0];selected=-1;resultClaimed=false;renderer.particles=[];renderer.texts=[];renderer.arcs=[];accumulator=0;screen='battle';modal=null;renderUI();audio.play('wave');}
function updateHUD(){if(screen!=='battle')return;if(battle.wave>0)document.querySelector('.tutorial')?.remove();const set=(id,text)=>{const el=document.getElementById(id);if(el&&el.textContent!==String(text))el.textContent=text;};set('lives',battle.lives);set('battle-gold',battle.gold);set('wave-count',`${battle.wave} / ${battle.stage.waves}`);set('speed',battle.speed+'×');const wave=document.querySelector('#wave-button'),canWave=!battle.enemies.length&&!battle.spawnQueue.length&&battle.wave<battle.stage.waves;wave.disabled=!canWave;wave.textContent=canWave?(battle.wave?'Next wave ▶':'Start wave ▶'):'Defending…';const skill=document.querySelector('.skill-button');skill.disabled=battle.skillCD>0||!battle.enemies.length;set('skill-label',battle.skillCD>0?`${Math.ceil(battle.skillCD)}s`:`${battle.hero.skill} [Q]`);document.querySelectorAll('.build-card').forEach(el=>{const t=TOWERS.find(t=>t.id===el.dataset.id);el.classList.toggle('active',build===t.id);el.disabled=battle.gold<t.cost;});set('hint-title',canWave&&battle.wave?'Wave cleared!':battle.enemies.length?`${battle.enemies.length} enemies on the road`:'Choose a build site');set('hint-detail',canWave&&battle.wave?'Reinforce your defenses, then call the next wave.':`${TOWERS.find(t=>t.id===build).name} selected · Tap a + to build`);
 const boss=battle.enemies.find(e=>e.type==='boss'),slot=document.querySelector('#boss-slot');if(boss){if(!slot.firstChild)slot.innerHTML=`<div class="bossbar"><strong>Briarhorn · Forest Tyrant</strong><div class="boss-track"><div></div></div></div>`;slot.querySelector('.boss-track div').style.width=Math.max(0,boss.hp/boss.maxHP*100)+'%';}else if(slot.firstChild)slot.innerHTML='';
}
function action(name,id){audio.unlock();audio.play('click');if(modal&&screen==='battle'&&!['sound','resume','restart','leave','confirm-leave','claim'].includes(name))return;
 switch(name){case 'home':case 'stages':case 'team':case 'collection':case 'shop':navigate(name);break;
 case 'stage':{const n=Number(id);if(n>=1&&n<=save.unlocked){stage=n;renderUI();}break;}
 case 'hero':if(HEROES.some(h=>h.id===id)){save.hero=id;store();renderUI();}break;
 case 'team-tower':if(save.team.includes(id))save.team=save.team.filter(t=>t!==id);else if(save.team.length<4&&TOWERS.some(t=>t.id===id))save.team.push(id);else notify('Select a tower to remove before adding another.');if(save.team.length===4)store();renderUI();break;
 case 'battle':startBattle();break;
 case 'build':build=id;selected=-1;towerContext();updateHUD();break;
 case 'site':{const site=Number(id);if(battle.pause)return;selected=site;const t=battle.towers.find(t=>t.site===site);if(t)towerContext();else if(battle.place(site,build)){selected=site;towerContext();updateHUD();}else notify('Not enough battle gold for this tower.');break;}
 case 'deselect':selected=-1;towerContext();break;
 case 'upgrade':if(battle.upgrade(selected)){towerContext();updateHUD();}break;
 case 'sell':if(battle.sell(selected)){selected=-1;towerContext();updateHUD();audio.play('sell');}break;
 case 'wave':if(battle.nextWave()){document.querySelector('.tutorial')?.remove();selected=-1;towerContext();updateHUD();}break;
 case 'skill':if(!battle.skill())notify('Your hero is not ready yet.');updateHUD();break;
 case 'speed':battle.speed=battle.speed===1?2:1;updateHUD();break;
 case 'pause':battle.pause=true;modal='pause';renderUI();break;
 case 'resume':battle.pause=false;modal=null;accumulator=0;renderUI();break;
 case 'restart':startBattle();break;
 case 'leave':modal='leave';renderUI();break;
 case 'confirm-leave':battle=null;renderer.particles=[];renderer.texts=[];navigate('home');break;
 case 'claim':if(!resultClaimed&&battle.state==='victory'){resultClaimed=true;const s=battle.stage.id,stars=battle.lives===20?3:battle.lives>=10?2:1;grant(save,'gold',battle.stage.reward);if(!save.stars[s])grant(save,'gems',25);save.stars[s]=Math.max(save.stars[s]||0,stars);save.unlocked=Math.max(save.unlocked,Math.min(12,s+1));store();audio.play('reward');battle=null;navigate('stages');notify('Rewards collected. The frontier opens before you.');}break;
 case 'train':{const t=TOWERS.find(t=>t.id===id);if(t&&save.levels[id]<20&&spend(save,'gold',save.levels[id]*100)){save.levels[id]++;store();audio.play('upgrade');renderUI();notify(`${t.name} trained to level ${save.levels[id]}.`);}break;}
 case 'summon':if(spend(save,'gems',40)){const random=rng(48271+save.summons*9127),t=TOWERS[Math.floor(random()*TOWERS.length)];save.summons++;const duplicate=save.levels[t.id]>=20;if(duplicate)grant(save,'gold',100);else save.levels[t.id]++;store();modal={type:'summon',id:t.id,duplicate};audio.play('reward');renderUI();}break;
 case 'exchange':if(spend(save,'gems',30)){grant(save,'gold',300);store();renderUI();audio.play('reward');notify('300 gold added to your purse.');}break;
 case 'guide':case 'settings':modal=name;renderUI();break;
 case 'sound':save.sound=!save.sound;audio.enabled=save.sound;store();renderUI();break;
 case 'close':modal=null;renderUI();break;
 }
}
ui.addEventListener('click',e=>{const button=e.target.closest('[data-action]');if(button&&!button.disabled)action(button.dataset.action,button.dataset.id);});
ui.addEventListener('change',e=>{if(e.target.id==='targeting'){const t=battle.towers.find(t=>t.site===selected);if(t&&['first','strongest'].includes(e.target.value)){t.targeting=e.target.value;battle.actions.push({at:battle.time,type:'targeting',site:selected,value:t.targeting});}}});
window.addEventListener('keydown',e=>{if(e.key==='Tab'&&modal){const focusable=[...ui.querySelectorAll('.modal button:not(:disabled), .modal select')];const first=focusable[0],end=focusable.at(-1);if(e.shiftKey&&document.activeElement===first){end?.focus();e.preventDefault();}else if(!e.shiftKey&&document.activeElement===end){first?.focus();e.preventDefault();}return;}if(e.repeat||['SELECT','INPUT','TEXTAREA'].includes(e.target.tagName))return;if(screen!=='battle'){if(e.key==='Escape'&&modal){modal=null;renderUI();}return;}if(['Space','Escape'].includes(e.code)){e.preventDefault();if(['victory','defeat'].includes(battle.state))return;action(battle.pause?'resume':'pause');}else if(!modal){if(e.code==='KeyQ')action('skill');if(/^Digit[1-4]$/.test(e.code))action('build',save.team[Number(e.code.slice(-1))-1]);}});
window.addEventListener('resize',()=>{if(screen==='battle')renderUI();});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&screen==='battle'&&battle&&!battle.pause&&['ready','running'].includes(battle.state)){battle.pause=true;modal='pause';renderUI();}last=0;accumulator=0;});
function frame(now){const dt=last?Math.min((now-last)/1000,.1):0;last=now;fps=fps*.95+(dt?1/dt:60)*.05;if(screen==='battle'&&battle){if(!battle.pause){accumulator+=dt*battle.speed;let steps=0;while(accumulator>=1/60&&steps++<12){battle.step(1/60);accumulator-=1/60;}}
 const events=battle.events.splice(0);for(const e of events){renderer.event(e);if(['attack','build','upgrade','skill','victory','defeat','wave','boss'].includes(e.type))audio.play(e.type);if(e.type==='boss-warning')notify('Final wave · Briarhorn approaches!');if(e.type==='enrage')notify('Briarhorn is enraged!');if(e.type==='victory'||e.type==='defeat'){modal=e.type;renderUI();}}hudTime+=dt;if(hudTime>.15){hudTime=0;updateHUD();}}
 if(screen==='home'||screen==='battle'||screen!==lastRenderedScreen){renderer.draw(battle,{screen,selected,build,hero:save.hero,time:now/1000,dt});lastRenderedScreen=screen;}if(toastUntil&&now>toastUntil){toastElement.classList.remove('show');toastUntil=0;}renderCount++;requestAnimationFrame(frame);}
renderUI();validateContent();loadArt().then(()=>{screen='home';renderUI();requestAnimationFrame(frame);});
if(import.meta.env.DEV){window.__goldward={get battle(){return battle;},get save(){return save;},get screen(){return screen;},get metrics(){return {fps,particles:renderer.particles.length,enemies:battle?.enemies.length||0,projectiles:battle?.shots.length||0,frames:renderCount};},start:()=>startBattle(),action,snapshot:()=>battle?.snapshot()};}
if('serviceWorker' in navigator&&import.meta.env.PROD&&location.protocol!=='file:')navigator.serviceWorker.register('./sw.js').catch(()=>notify('Offline caching unavailable. Run the local build server to play offline.'));
