import {TOWERS,HEROES} from './data.js';
export const SAVE_KEY='goldward.save';
export const defaults=()=>({version:2,gold:420,gems:120,unlocked:1,stars:{},levels:Object.fromEntries(TOWERS.map(t=>[t.id,1])),hero:'lyra',team:['archer','cannon','frost','storm'],summons:0,sound:true});
const int=(x,f,min=0,max=1e8)=>Number.isSafeInteger(x)&&x>=min&&x<=max?x:f;
export function normalize(raw){if(!raw||typeof raw!=='object'||Array.isArray(raw))throw Error('Invalid save');if(raw.version!==1&&raw.version!==2)throw Error('Unsupported save version');const d=defaults();d.gold=int(raw.gold,d.gold);d.gems=int(raw.gems,d.gems);d.unlocked=int(raw.unlocked,1,1,12);d.summons=int(raw.summons,0);d.sound=typeof raw.sound==='boolean'?raw.sound:true;d.hero=HEROES.some(h=>h.id===raw.hero)?raw.hero:d.hero;d.team=Array.isArray(raw.team)?[...new Set(raw.team.filter(id=>TOWERS.some(t=>t.id===id)))].slice(0,4):d.team;if(d.team.length!==4)d.team=defaults().team;for(const t of TOWERS)d.levels[t.id]=int(raw.levels?.[t.id],1,1,20);for(let i=1;i<=12;i++){const s=int(raw.stars?.[i],0,0,3);if(s)d.stars[i]=s;}return d;}
export function load(storage){try{storage??=globalThis.localStorage;}catch{return defaults();}for(const key of [SAVE_KEY,SAVE_KEY+'.backup'])try{const raw=storage.getItem(key);if(raw)return normalize(JSON.parse(raw));}catch{}return defaults();}
export function persist(save,storage){try{storage??=globalThis.localStorage;const clean=normalize(save),text=JSON.stringify(clean),old=storage.getItem(SAVE_KEY);if(old){try{normalize(JSON.parse(old));storage.setItem(SAVE_KEY+'.backup',old);}catch{}}storage.setItem(SAVE_KEY,text);return true;}catch{return false;}}
export function spend(save,currency,amount){if(!['gold','gems'].includes(currency)||!Number.isSafeInteger(amount)||amount<0||!Number.isSafeInteger(save[currency])||save[currency]<amount)return false;save[currency]-=amount;return true;}
export function grant(save,currency,amount){if(!['gold','gems'].includes(currency)||!Number.isSafeInteger(amount)||amount<0||!Number.isSafeInteger(save[currency])||save[currency]+amount>1e8)return false;save[currency]+=amount;return true;}
